export const PERMISSION_CATEGORIES = {
    DASHBOARD: 'Dashboard & Insights',
    INSTITUTION: 'Institution Setup',
    USER: 'User & Account Governance',
    ACADEMIC: 'Academic Operations',
    EXAM: 'Examination Controls',
    PROCTORING: 'Proctoring & Discipline',
    COMMUNICATION: 'Communication',
    SYSTEM: 'System Support',
} as const;

export type PermissionCategory = keyof typeof PERMISSION_CATEGORIES;
export type PermissionScope = 'global' | 'institution' | 'department' | 'course' | 'self';

export interface Permission {
    id: string;
    moduleKey: string;
    actionKey: string;
    scope: PermissionScope;
    name: string;
    description: string;
    category: PermissionCategory;
}

export interface SystemRoleBlueprint {
    description: string;
    responsibilities: string[];
    permissionKeys: string[];
}

export const PERMISSIONS: Record<string, Permission> = {
    VIEW_DASHBOARD: {
        id: 'dashboard:view',
        moduleKey: 'dashboard',
        actionKey: 'view',
        scope: 'self',
        name: 'View Dashboard',
        description: 'Access the primary role dashboard and operational summaries.',
        category: 'DASHBOARD',
    },

    VIEW_INSTITUTIONS: {
        id: 'institutions:view',
        moduleKey: 'institutions',
        actionKey: 'view',
        scope: 'global',
        name: 'View Institutions',
        description: 'Review institution records and setup details.',
        category: 'INSTITUTION',
    },
    CREATE_INSTITUTIONS: {
        id: 'institutions:create',
        moduleKey: 'institutions',
        actionKey: 'create',
        scope: 'global',
        name: 'Create Institutions',
        description: 'Add new institution records to the platform.',
        category: 'INSTITUTION',
    },
    UPDATE_INSTITUTIONS: {
        id: 'institutions:update',
        moduleKey: 'institutions',
        actionKey: 'update',
        scope: 'global',
        name: 'Update Institutions',
        description: 'Edit institution details, ownership, and related metadata.',
        category: 'INSTITUTION',
    },
    DELETE_INSTITUTIONS: {
        id: 'institutions:delete',
        moduleKey: 'institutions',
        actionKey: 'delete',
        scope: 'global',
        name: 'Delete Institutions',
        description: 'Remove institution records from the platform.',
        category: 'INSTITUTION',
    },

    VIEW_DEPARTMENTS: {
        id: 'departments:view',
        moduleKey: 'departments',
        actionKey: 'view',
        scope: 'institution',
        name: 'View Departments',
        description: 'Review department structures and ownership.',
        category: 'INSTITUTION',
    },
    CREATE_DEPARTMENTS: {
        id: 'departments:create',
        moduleKey: 'departments',
        actionKey: 'create',
        scope: 'institution',
        name: 'Create Departments',
        description: 'Add new departments inside an institution.',
        category: 'INSTITUTION',
    },
    UPDATE_DEPARTMENTS: {
        id: 'departments:update',
        moduleKey: 'departments',
        actionKey: 'update',
        scope: 'institution',
        name: 'Update Departments',
        description: 'Edit department records and organizational details.',
        category: 'INSTITUTION',
    },
    DELETE_DEPARTMENTS: {
        id: 'departments:delete',
        moduleKey: 'departments',
        actionKey: 'delete',
        scope: 'institution',
        name: 'Delete Departments',
        description: 'Remove departments that are no longer active.',
        category: 'INSTITUTION',
    },
    IMPORT_DEPARTMENTS: {
        id: 'departments:import',
        moduleKey: 'departments',
        actionKey: 'import',
        scope: 'institution',
        name: 'Import Departments',
        description: 'Bulk import department records from external files.',
        category: 'INSTITUTION',
    },

    VIEW_SEMESTERS: {
        id: 'semesters:view',
        moduleKey: 'semesters',
        actionKey: 'view',
        scope: 'institution',
        name: 'View Semesters',
        description: 'View active and historical academic terms.',
        category: 'INSTITUTION',
    },
    CREATE_SEMESTERS: {
        id: 'semesters:create',
        moduleKey: 'semesters',
        actionKey: 'create',
        scope: 'institution',
        name: 'Create Semesters',
        description: 'Create new academic terms and enrollment windows.',
        category: 'INSTITUTION',
    },
    UPDATE_SEMESTERS: {
        id: 'semesters:update',
        moduleKey: 'semesters',
        actionKey: 'update',
        scope: 'institution',
        name: 'Update Semesters',
        description: 'Modify term schedules, dates, and visibility.',
        category: 'INSTITUTION',
    },
    DELETE_SEMESTERS: {
        id: 'semesters:delete',
        moduleKey: 'semesters',
        actionKey: 'delete',
        scope: 'institution',
        name: 'Delete Semesters',
        description: 'Delete academic terms that should not remain available.',
        category: 'INSTITUTION',
    },

    VIEW_ROOMS: {
        id: 'rooms:view',
        moduleKey: 'rooms',
        actionKey: 'view',
        scope: 'institution',
        name: 'View Rooms',
        description: 'Review available examination rooms and venues for the institution.',
        category: 'INSTITUTION',
    },
    CREATE_ROOMS: {
        id: 'rooms:create',
        moduleKey: 'rooms',
        actionKey: 'create',
        scope: 'institution',
        name: 'Create Rooms',
        description: 'Add new examination rooms or venues for the institution.',
        category: 'INSTITUTION',
    },
    UPDATE_ROOMS: {
        id: 'rooms:update',
        moduleKey: 'rooms',
        actionKey: 'update',
        scope: 'institution',
        name: 'Update Rooms',
        description: 'Edit room metadata, labels, codes, and venue details.',
        category: 'INSTITUTION',
    },
    DELETE_ROOMS: {
        id: 'rooms:delete',
        moduleKey: 'rooms',
        actionKey: 'delete',
        scope: 'institution',
        name: 'Delete Rooms',
        description: 'Remove rooms that are no longer available for examinations.',
        category: 'INSTITUTION',
    },

    VIEW_USERS: {
        id: 'users:view',
        moduleKey: 'users',
        actionKey: 'view',
        scope: 'institution',
        name: 'View Users',
        description: 'Review user accounts, roles, and academic assignments.',
        category: 'USER',
    },
    CREATE_SUPERADMIN_USERS: {
        id: 'users:create_superadmin',
        moduleKey: 'users',
        actionKey: 'create_superadmin',
        scope: 'global',
        name: 'Create Superadmin Accounts',
        description: 'Provision or invite superadmin accounts.',
        category: 'USER',
    },
    CREATE_ADMIN_USERS: {
        id: 'users:create_admin',
        moduleKey: 'users',
        actionKey: 'create_admin',
        scope: 'department',
        name: 'Create Admin Accounts',
        description: 'Provision or invite admin accounts within the allowed scope.',
        category: 'USER',
    },
    CREATE_STAFF_USERS: {
        id: 'users:create_staff',
        moduleKey: 'users',
        actionKey: 'create_staff',
        scope: 'course',
        name: 'Create Staff Accounts',
        description: 'Create or invite instructor, proctor, or support-adjacent staff accounts.',
        category: 'USER',
    },
    CREATE_STUDENT_USERS: {
        id: 'users:create_student',
        moduleKey: 'users',
        actionKey: 'create_student',
        scope: 'course',
        name: 'Create Student Accounts',
        description: 'Create student accounts inside the permitted academic scope.',
        category: 'USER',
    },
    UPDATE_USERS: {
        id: 'users:update',
        moduleKey: 'users',
        actionKey: 'update',
        scope: 'institution',
        name: 'Update Users',
        description: 'Update user metadata, academic assignments, and access posture.',
        category: 'USER',
    },
    DELETE_USERS: {
        id: 'users:delete',
        moduleKey: 'users',
        actionKey: 'delete',
        scope: 'institution',
        name: 'Delete Users',
        description: 'Deactivate or remove user accounts in the permitted scope.',
        category: 'USER',
    },

    VIEW_ACCESS_CONTROL: {
        id: 'access_control:view',
        moduleKey: 'access_control',
        actionKey: 'view',
        scope: 'global',
        name: 'View Access Control',
        description: 'Open the RBAC workspace and review catalog coverage.',
        category: 'SYSTEM',
    },
    CREATE_ROLE: {
        id: 'access_control:create_role',
        moduleKey: 'access_control',
        actionKey: 'create_role',
        scope: 'global',
        name: 'Create Role',
        description: 'Define and add new role records to the platform.',
        category: 'SYSTEM',
    },
    MANAGE_ROLE_CATALOG: {
        id: 'access_control:manage_roles',
        moduleKey: 'access_control',
        actionKey: 'manage_roles',
        scope: 'global',
        name: 'Manage Roles',
        description: 'Create, update, and maintain role definitions.',
        category: 'SYSTEM',
    },
    MANAGE_PERMISSION_CATALOG: {
        id: 'access_control:manage_permissions',
        moduleKey: 'access_control',
        actionKey: 'manage_permissions',
        scope: 'global',
        name: 'Manage Permissions',
        description: 'Maintain permission definitions, modules, and labels.',
        category: 'SYSTEM',
    },
    MANAGE_ROLE_ASSIGNMENTS: {
        id: 'access_control:manage_assignments',
        moduleKey: 'access_control',
        actionKey: 'manage_assignments',
        scope: 'global',
        name: 'Manage Assignments',
        description: 'Assign roles to users and adjust access ownership.',
        category: 'SYSTEM',
    },

    VIEW_COURSES: {
        id: 'courses:view',
        moduleKey: 'courses',
        actionKey: 'view',
        scope: 'department',
        name: 'View Courses',
        description: 'Review courses within the allowed institution or department scope.',
        category: 'ACADEMIC',
    },
    CREATE_COURSES: {
        id: 'courses:create',
        moduleKey: 'courses',
        actionKey: 'create',
        scope: 'department',
        name: 'Create Courses',
        description: 'Create new courses for a department.',
        category: 'ACADEMIC',
    },
    UPDATE_COURSES: {
        id: 'courses:update',
        moduleKey: 'courses',
        actionKey: 'update',
        scope: 'department',
        name: 'Update Courses',
        description: 'Edit course titles, codes, and supporting details.',
        category: 'ACADEMIC',
    },
    DELETE_COURSES: {
        id: 'courses:delete',
        moduleKey: 'courses',
        actionKey: 'delete',
        scope: 'department',
        name: 'Delete Courses',
        description: 'Remove courses that should no longer be offered.',
        category: 'ACADEMIC',
    },

    VIEW_SECTIONS: {
        id: 'sections:view',
        moduleKey: 'sections',
        actionKey: 'view',
        scope: 'course',
        name: 'View Sections',
        description: 'Review class sections inside the allowed course or department scope.',
        category: 'ACADEMIC',
    },
    CREATE_SECTIONS: {
        id: 'sections:create',
        moduleKey: 'sections',
        actionKey: 'create',
        scope: 'course',
        name: 'Create Sections',
        description: 'Create new class sections for a course.',
        category: 'ACADEMIC',
    },
    UPDATE_SECTIONS: {
        id: 'sections:update',
        moduleKey: 'sections',
        actionKey: 'update',
        scope: 'course',
        name: 'Update Sections',
        description: 'Edit section naming, year level, and related metadata.',
        category: 'ACADEMIC',
    },
    DELETE_SECTIONS: {
        id: 'sections:delete',
        moduleKey: 'sections',
        actionKey: 'delete',
        scope: 'course',
        name: 'Delete Sections',
        description: 'Remove obsolete or incorrectly configured sections.',
        category: 'ACADEMIC',
    },

    VIEW_SUBJECTS: {
        id: 'subjects:view',
        moduleKey: 'subjects',
        actionKey: 'view',
        scope: 'department',
        name: 'View Subjects',
        description: 'Review the subject catalog and subject metadata.',
        category: 'ACADEMIC',
    },
    CREATE_SUBJECTS: {
        id: 'subjects:create',
        moduleKey: 'subjects',
        actionKey: 'create',
        scope: 'department',
        name: 'Create Subjects',
        description: 'Create new subject records in the shared catalog.',
        category: 'ACADEMIC',
    },
    UPDATE_SUBJECTS: {
        id: 'subjects:update',
        moduleKey: 'subjects',
        actionKey: 'update',
        scope: 'department',
        name: 'Update Subjects',
        description: 'Edit subject records, titles, codes, and offerability settings.',
        category: 'ACADEMIC',
    },
    DELETE_SUBJECTS: {
        id: 'subjects:delete',
        moduleKey: 'subjects',
        actionKey: 'delete',
        scope: 'department',
        name: 'Delete Subjects',
        description: 'Delete subjects that should no longer be retained in the catalog.',
        category: 'ACADEMIC',
    },

    VIEW_SUBJECT_OFFERINGS: {
        id: 'subject_offerings:view',
        moduleKey: 'subject_offerings',
        actionKey: 'view',
        scope: 'course',
        name: 'View Subject Offerings',
        description: 'Review offered subjects, target scope, and term coverage.',
        category: 'ACADEMIC',
    },
    OFFER_SUBJECTS: {
        id: 'subject_offerings:offer',
        moduleKey: 'subject_offerings',
        actionKey: 'offer',
        scope: 'course',
        name: 'Offer Subjects',
        description:
            'Create subject offerings and assign them to departments, courses, and sections.',
        category: 'ACADEMIC',
    },
    APPROVE_SUBJECT_OFFERINGS: {
        id: 'subject_offerings:approve',
        moduleKey: 'subject_offerings',
        actionKey: 'approve',
        scope: 'department',
        name: 'Approve Subject Offerings',
        description: 'Approve or finalize offered-subject coverage before delivery.',
        category: 'ACADEMIC',
    },
    UPDATE_SUBJECT_OFFERINGS: {
        id: 'subject_offerings:update',
        moduleKey: 'subject_offerings',
        actionKey: 'update',
        scope: 'course',
        name: 'Update Subject Offerings',
        description: 'Adjust scope, term, sections, and lifecycle status of offered subjects.',
        category: 'ACADEMIC',
    },
    DELETE_SUBJECT_OFFERINGS: {
        id: 'subject_offerings:delete',
        moduleKey: 'subject_offerings',
        actionKey: 'delete',
        scope: 'course',
        name: 'Delete Subject Offerings',
        description: 'Delete offered-subject records that should no longer exist.',
        category: 'ACADEMIC',
    },
    VIEW_SUBJECT_REQUESTS: {
        id: 'subject_requests:view',
        moduleKey: 'subject_requests',
        actionKey: 'view',
        scope: 'course',
        name: 'View Subject Requests',
        description: 'Review instructor subject-request and enrollment-request records.',
        category: 'ACADEMIC',
    },
    REQUEST_SUBJECTS: {
        id: 'subject_requests:request',
        moduleKey: 'subject_requests',
        actionKey: 'request',
        scope: 'course',
        name: 'Request Subjects',
        description: 'Submit subject or offered-subject requests for instructor assignment.',
        category: 'ACADEMIC',
    },
    APPROVE_SUBJECT_REQUESTS: {
        id: 'subject_requests:approve',
        moduleKey: 'subject_requests',
        actionKey: 'approve',
        scope: 'department',
        name: 'Approve Subject Requests',
        description: 'Approve pending subject-request workflows.',
        category: 'ACADEMIC',
    },
    REJECT_SUBJECT_REQUESTS: {
        id: 'subject_requests:reject',
        moduleKey: 'subject_requests',
        actionKey: 'reject',
        scope: 'department',
        name: 'Reject Subject Requests',
        description: 'Reject pending subject-request workflows.',
        category: 'ACADEMIC',
    },
    UNAPPROVE_SUBJECT_REQUESTS: {
        id: 'subject_requests:unapprove',
        moduleKey: 'subject_requests',
        actionKey: 'unapprove',
        scope: 'department',
        name: 'Unapprove Subject Requests',
        description: 'Move approved subject requests back to pending when reassessment is needed.',
        category: 'ACADEMIC',
    },
    VIEW_CLASSROOMS: {
        id: 'classrooms:view',
        moduleKey: 'classrooms',
        actionKey: 'view',
        scope: 'course',
        name: 'View Classrooms',
        description: 'Review class sections and enrollments inside the allowed course scope.',
        category: 'ACADEMIC',
    },
    CREATE_CLASSROOMS: {
        id: 'classrooms:create',
        moduleKey: 'classrooms',
        actionKey: 'create',
        scope: 'course',
        name: 'Create Classrooms',
        description: 'Create new classrooms for a subject and section.',
        category: 'ACADEMIC',
    },
    UPDATE_CLASSROOMS: {
        id: 'classrooms:update',
        moduleKey: 'classrooms',
        actionKey: 'update',
        scope: 'course',
        name: 'Update Classrooms',
        description: 'Edit classroom details, instructors, and student lists.',
        category: 'ACADEMIC',
    },
    DELETE_CLASSROOMS: {
        id: 'classrooms:delete',
        moduleKey: 'classrooms',
        actionKey: 'delete',
        scope: 'course',
        name: 'Delete Classrooms',
        description: 'Remove obsolete or incorrectly configured classrooms.',
        category: 'ACADEMIC',
    },
    VIEW_STUDENT_CLASSROOMS: {
        id: 'classrooms:view_enrolled',
        moduleKey: 'classrooms',
        actionKey: 'view_enrolled',
        scope: 'self',
        name: 'View Enrolled Classrooms',
        description: 'View the subjects and sections you are currently enrolled in.',
        category: 'ACADEMIC',
    },

    VIEW_STUDENT_WHITELIST: {
        id: 'student_whitelist:view',
        moduleKey: 'student_whitelist',
        actionKey: 'view',
        scope: 'course',
        name: 'View Student Whitelist',
        description: 'Review whitelisted student accounts and their academic placement.',
        category: 'USER',
    },
    CREATE_STUDENT_WHITELIST: {
        id: 'student_whitelist:create',
        moduleKey: 'student_whitelist',
        actionKey: 'create',
        scope: 'course',
        name: 'Create Student Whitelist Records',
        description: 'Add students to the whitelist individually.',
        category: 'USER',
    },
    UPDATE_STUDENT_WHITELIST: {
        id: 'student_whitelist:update',
        moduleKey: 'student_whitelist',
        actionKey: 'update',
        scope: 'course',
        name: 'Update Student Whitelist Records',
        description: 'Correct student whitelist data and academic assignments.',
        category: 'USER',
    },
    DELETE_STUDENT_WHITELIST: {
        id: 'student_whitelist:delete',
        moduleKey: 'student_whitelist',
        actionKey: 'delete',
        scope: 'course',
        name: 'Delete Student Whitelist Records',
        description: 'Remove individual students from the whitelist.',
        category: 'USER',
    },
    IMPORT_STUDENT_WHITELIST: {
        id: 'student_whitelist:import',
        moduleKey: 'student_whitelist',
        actionKey: 'import',
        scope: 'course',
        name: 'Import Student Whitelist',
        description: 'Bulk import whitelist records from external files.',
        category: 'USER',
    },
    PURGE_STUDENT_WHITELIST: {
        id: 'student_whitelist:purge',
        moduleKey: 'student_whitelist',
        actionKey: 'purge',
        scope: 'course',
        name: 'Purge Student Whitelist',
        description: 'Clear whitelist records for a scoped academic segment.',
        category: 'USER',
    },

    VIEW_EXAMINATION_SETTINGS: {
        id: 'examination_settings:view',
        moduleKey: 'examination_settings',
        actionKey: 'view',
        scope: 'global',
        name: 'View Examination Settings',
        description: 'Review system-wide examination defaults and policy baselines.',
        category: 'EXAM',
    },
    UPDATE_EXAMINATION_SETTINGS: {
        id: 'examination_settings:update',
        moduleKey: 'examination_settings',
        actionKey: 'update',
        scope: 'global',
        name: 'Update Examination Settings',
        description: 'Update default duration, scoring, proctoring, and device controls.',
        category: 'EXAM',
    },
    VIEW_TELEMETRY_SETTINGS: {
        id: 'telemetry:view_settings',
        moduleKey: 'telemetry',
        actionKey: 'view_settings',
        scope: 'global',
        name: 'View Telemetry Settings',
        description:
            'Review support-managed telemetry operations, rule overrides, and sandbox settings.',
        category: 'SYSTEM',
    },
    UPDATE_TELEMETRY_SETTINGS: {
        id: 'telemetry:update_settings',
        moduleKey: 'telemetry',
        actionKey: 'update_settings',
        scope: 'global',
        name: 'Update Telemetry Settings',
        description:
            'Update global telemetry operations, rule overrides, and MediaPipe sandbox settings.',
        category: 'SYSTEM',
    },
    VIEW_TELEMETRY_HEALTH: {
        id: 'telemetry:view_health',
        moduleKey: 'telemetry',
        actionKey: 'view_health',
        scope: 'global',
        name: 'View Telemetry Health',
        description: 'Inspect telemetry queue health, ingestion mode, and operational status.',
        category: 'SYSTEM',
    },
    READ_AUDIO_CALIBRATION: {
        id: 'audio_calibration:read',
        moduleKey: 'audio_calibration',
        actionKey: 'read',
        scope: 'global',
        name: 'Read Audio Calibration',
        description: 'Review global audio anomaly calibration settings.',
        category: 'SYSTEM',
    },
    MANAGE_AUDIO_CALIBRATION: {
        id: 'audio_calibration:manage',
        moduleKey: 'audio_calibration',
        actionKey: 'manage',
        scope: 'global',
        name: 'Manage Audio Calibration',
        description: 'Update global audio anomaly calibration settings.',
        category: 'SYSTEM',
    },
    READ_AUDIO_INCIDENTS: {
        id: 'audio_incidents:read',
        moduleKey: 'audio_incidents',
        actionKey: 'read',
        scope: 'global',
        name: 'Read Audio Incidents',
        description: 'Review audio anomaly incidents in monitoring surfaces.',
        category: 'SYSTEM',
    },
    VIEW_EXAMINATIONS: {
        id: 'examinations:view',
        moduleKey: 'examinations',
        actionKey: 'view',
        scope: 'self',
        name: 'View Examinations',
        description: 'Review exam schedules, assignments, and accessible sessions.',
        category: 'EXAM',
    },
    TAKE_EXAMINATIONS: {
        id: 'examinations:take',
        moduleKey: 'examinations',
        actionKey: 'take',
        scope: 'self',
        name: 'Take Examinations',
        description: 'Launch and take assigned examinations.',
        category: 'EXAM',
    },
    VIEW_RESULTS: {
        id: 'results:view',
        moduleKey: 'results',
        actionKey: 'view',
        scope: 'self',
        name: 'View Results',
        description: 'Review examination results and completion outcomes.',
        category: 'EXAM',
    },
    VIEW_NOTIFICATIONS: {
        id: 'notifications:view',
        moduleKey: 'notifications',
        actionKey: 'view',
        scope: 'self',
        name: 'View Notifications',
        description:
            'View and acknowledge in-app workflow notifications addressed to your account.',
        category: 'COMMUNICATION',
    },
    VIEW_MESSAGES: {
        id: 'messages:view',
        moduleKey: 'messages',
        actionKey: 'view',
        scope: 'self',
        name: 'View Messages',
        description: 'Read and view direct messages and conversations.',
        category: 'COMMUNICATION',
    },
    CREATE_MESSAGES: {
        id: 'messages:create',
        moduleKey: 'messages',
        actionKey: 'create',
        scope: 'self',
        name: 'Create Messages',
        description: 'Start new direct conversations and send messages.',
        category: 'COMMUNICATION',
    },

    BYPASS_PUBLISHED_EXAM_LOCK: {
        id: 'examinations:bypass_publish_lock',
        moduleKey: 'examinations',
        actionKey: 'bypass_publish_lock',
        scope: 'global',
        name: 'Bypass Published Exam Lock',
        description:
            'Allow modification of exam settings and content even after the exam has been published.',
        category: 'EXAM',
    },

    VIEW_PROCTORING_SESSIONS: {
        id: 'proctoring:view_sessions',
        moduleKey: 'proctoring',
        actionKey: 'view_sessions',
        scope: 'institution',
        name: 'View Proctoring Sessions',
        description: 'Open live or historical monitoring sessions.',
        category: 'PROCTORING',
    },
    MONITOR_PROCTORING: {
        id: 'proctoring:monitor',
        moduleKey: 'proctoring',
        actionKey: 'monitor',
        scope: 'institution',
        name: 'Monitor Proctoring Sessions',
        description: 'Monitor examinees, flags, and live activity during exams.',
        category: 'PROCTORING',
    },
    RESPOND_TO_FLAGS: {
        id: 'proctoring:respond_to_flags',
        moduleKey: 'proctoring',
        actionKey: 'respond_to_flags',
        scope: 'institution',
        name: 'Respond to Flags',
        description: 'Handle suspicious events, violations, and proctor interventions.',
        category: 'PROCTORING',
    },

    VIEW_INCIDENTS: {
        id: 'incidents:view',
        moduleKey: 'incidents',
        actionKey: 'view',
        scope: 'institution',
        name: 'View Incidents',
        description: 'Review captured incidents, flags, and discipline records.',
        category: 'PROCTORING',
    },
    REVIEW_INCIDENTS: {
        id: 'incidents:review',
        moduleKey: 'incidents',
        actionKey: 'review',
        scope: 'institution',
        name: 'Review Incidents',
        description: 'Assess incidents and record discipline outcomes.',
        category: 'PROCTORING',
    },
    EXPORT_INCIDENTS: {
        id: 'incidents:export',
        moduleKey: 'incidents',
        actionKey: 'export',
        scope: 'institution',
        name: 'Export Incidents',
        description: 'Export discipline records and supporting evidence.',
        category: 'PROCTORING',
    },

    VIEW_REPORTS: {
        id: 'reports:view',
        moduleKey: 'reports',
        actionKey: 'view',
        scope: 'institution',
        name: 'View Reports',
        description: 'Review administrative and compliance reports.',
        category: 'DASHBOARD',
    },
    EXPORT_REPORTS: {
        id: 'reports:export',
        moduleKey: 'reports',
        actionKey: 'export',
        scope: 'institution',
        name: 'Export Reports',
        description: 'Export analytical or governance reports for sharing.',
        category: 'DASHBOARD',
    },

    VIEW_CALENDAR: {
        id: 'calendar:view',
        moduleKey: 'calendar',
        actionKey: 'view',
        scope: 'institution',
        name: 'View Calendar Events',
        description: 'Access and review institutional calendar events and announcements.',
        category: 'COMMUNICATION',
    },
    CREATE_CALENDAR: {
        id: 'calendar:create',
        moduleKey: 'calendar',
        actionKey: 'create',
        scope: 'institution',
        name: 'Create Calendar Events',
        description: 'Add new events and announcements to the institutional calendar.',
        category: 'COMMUNICATION',
    },
    UPDATE_CALENDAR: {
        id: 'calendar:update',
        moduleKey: 'calendar',
        actionKey: 'update',
        scope: 'institution',
        name: 'Update Calendar Events',
        description: 'Edit and manage existing institutional calendar events and announcements.',
        category: 'COMMUNICATION',
    },
    DELETE_CALENDAR: {
        id: 'calendar:delete',
        moduleKey: 'calendar',
        actionKey: 'delete',
        scope: 'institution',
        name: 'Delete Calendar Events',
        description: 'Remove events and announcements from the institutional calendar.',
        category: 'COMMUNICATION',
    },

    VIEW_ANNOUNCEMENTS: {
        id: 'announcement:view',
        moduleKey: 'announcements',
        actionKey: 'view',
        scope: 'institution',
        name: 'View Announcements',
        description: 'Access and read institutional announcements.',
        category: 'COMMUNICATION',
    },
    CREATE_ANNOUNCEMENTS: {
        id: 'announcement:create',
        moduleKey: 'announcements',
        actionKey: 'create',
        scope: 'institution',
        name: 'Create Announcements',
        description: 'Create new institutional announcements.',
        category: 'COMMUNICATION',
    },
    UPDATE_ANNOUNCEMENTS: {
        id: 'announcement:update',
        moduleKey: 'announcements',
        actionKey: 'update',
        scope: 'institution',
        name: 'Update Announcements',
        description: 'Edit and update existing institutional announcements.',
        category: 'COMMUNICATION',
    },
    DELETE_ANNOUNCEMENTS: {
        id: 'announcement:delete',
        moduleKey: 'announcements',
        actionKey: 'delete',
        scope: 'institution',
        name: 'Delete Announcements',
        description: 'Remove announcements from the institution.',
        category: 'COMMUNICATION',
    },

    VIEW_GUIDES: {
        id: 'guides:view',
        moduleKey: 'guides',
        actionKey: 'view',
        scope: 'self',
        name: 'View Guides',
        description: 'Access guides, help materials, and operator references.',
        category: 'SYSTEM',
    },
    MANAGE_ROOMS: {
        id: 'rooms:manage',
        moduleKey: 'rooms',
        actionKey: 'manage',
        scope: 'institution',
        name: 'Manage Rooms',
        description: 'Create, update, and delete examination rooms.',
        category: 'INSTITUTION',
    },
    MANAGE_SEMESTERS: {
        id: 'semesters:manage',
        moduleKey: 'semesters',
        actionKey: 'manage',
        scope: 'institution',
        name: 'Manage Semesters',
        description: 'Create, update, and delete academic semesters.',
        category: 'INSTITUTION',
    },
    MANAGE_DEPARTMENTS: {
        id: 'departments:manage',
        moduleKey: 'departments',
        actionKey: 'manage',
        scope: 'institution',
        name: 'Manage Departments',
        description: 'Create, update, and delete departments.',
        category: 'INSTITUTION',
    },
    MANAGE_INSTITUTIONS: {
        id: 'institutions:manage',
        moduleKey: 'institutions',
        actionKey: 'manage',
        scope: 'global',
        name: 'Manage Institutions',
        description: 'Create, update, and delete institutions.',
        category: 'INSTITUTION',
    },
    CROSS_TENANT_VIEW_INSTITUTIONS: {
        id: 'institutions:cross-tenant-view',
        moduleKey: 'institutions',
        actionKey: 'cross-tenant-view',
        scope: 'global',
        name: 'Cross Tenant View Institutions',
        description: 'View institution records and data across all tenants.',
        category: 'INSTITUTION',
    },
    VIEW_PERMISSIONS: {
        id: 'permissions:view',
        moduleKey: 'permissions',
        actionKey: 'view',
        scope: 'global',
        name: 'View Permissions',
        description: 'View access control permission assignments.',
        category: 'SYSTEM',
    },
    MANAGE_PERMISSIONS: {
        id: 'permissions:manage',
        moduleKey: 'permissions',
        actionKey: 'manage',
        scope: 'global',
        name: 'Manage Permissions',
        description: 'Modify role and user permission assignments.',
        category: 'SYSTEM',
    },
    VIEW_ASSESSMENTS: {
        id: 'assessments:view',
        moduleKey: 'assessments',
        actionKey: 'view',
        scope: 'self',
        name: 'View Assessments',
        description: 'View and read examinations and assessment setups.',
        category: 'EXAM',
    },
    MANAGE_ASSESSMENTS: {
        id: 'assessments:manage',
        moduleKey: 'assessments',
        actionKey: 'manage',
        scope: 'institution',
        name: 'Manage Assessments',
        description: 'Create, configure, and manage assessment structures.',
        category: 'EXAM',
    },
    GENERATE_QUESTION_PREVIEW: {
        id: 'ai:generate_questions',
        moduleKey: 'ai',
        actionKey: 'generate_questions',
        scope: 'institution',
        name: 'Generate Questions',
        description: 'Generate AI question previews from uploaded lesson PDFs.',
        category: 'EXAM',
    },
} as const;

export const SYSTEM_ROLE_BLUEPRINTS: Record<string, SystemRoleBlueprint> = {
    support: {
        description:
            'Global support role responsible for institution setup, governance, and RBAC control.',
        responsibilities: [
            'Handles institution, department, and semester configuration across the platform.',
            'Creates superadmin accounts and maintains the global RBAC workspace.',
            'Controls examination-wide default settings and governance baselines.',
        ],
        permissionKeys: [
            'dashboard:view',
            'institutions:view',
            'institutions:create',
            'institutions:update',
            'institutions:delete',
            'institutions:manage',
            'institutions:cross-tenant-view',
            'departments:view',
            'departments:create',
            'departments:update',
            'departments:delete',
            'departments:import',
            'departments:manage',
            'semesters:view',
            'semesters:create',
            'semesters:update',
            'semesters:delete',
            'semesters:manage',
            'rooms:view',
            'rooms:create',
            'rooms:update',
            'rooms:delete',
            'rooms:manage',
            'courses:view',
            'courses:create',
            'courses:update',
            'courses:delete',
            'sections:view',
            'sections:create',
            'sections:update',
            'sections:delete',
            'users:view',
            'users:create_superadmin',
            'access_control:view',
            'access_control:create_role',
            'access_control:manage_roles',
            'access_control:manage_permissions',
            'access_control:manage_assignments',
            'permissions:view',
            'permissions:manage',
            'examination_settings:view',
            'examination_settings:update',
            'telemetry:view_settings',
            'telemetry:update_settings',
            'telemetry:view_health',
            'audio_calibration:read',
            'audio_calibration:manage',
            'examinations:bypass_publish_lock',
            'assessments:view',
            'assessments:manage',
            'ai:generate_questions',
            'classrooms:view',
            'classrooms:create',
            'classrooms:update',
            'classrooms:delete',
            'notifications:view',
            'messages:view',
            'messages:create',
            'calendar:view',
            'calendar:create',
            'calendar:update',
            'calendar:delete',
            'announcement:view',
            'announcement:create',
            'announcement:update',
            'announcement:delete',
            'reports:view',
            'reports:export',
        ],
    },
    superadmin: {
        description:
            'Department-level system administrator for academic operations, approval, and oversight.',
        responsibilities: [
            'Owns courses and subjects, including CRUD, offering, and approval flows.',
            'Creates admin accounts and oversees whitelist coverage for the whole department.',
            'Reviews sections, reports, and department-wide academic readiness.',
        ],
        permissionKeys: [
            'dashboard:view',
            'institutions:view',
            'institutions:manage',
            'institutions:cross-tenant-view',
            'departments:view',
            'departments:create',
            'departments:update',
            'departments:import',
            'departments:manage',
            'semesters:view',
            'semesters:manage',
            'rooms:view',
            'rooms:create',
            'rooms:update',
            'rooms:delete',
            'rooms:manage',
            'users:view',
            'users:create_admin',
            'users:update',
            'courses:view',
            'courses:create',
            'courses:update',
            'courses:delete',
            'sections:view',
            'sections:create',
            'sections:update',
            'sections:delete',
            'subjects:view',
            'subjects:create',
            'subjects:update',
            'subjects:delete',
            'subject_offerings:view',
            'subject_offerings:offer',
            'subject_offerings:approve',
            'subject_offerings:update',
            'subject_offerings:delete',
            'subject_requests:view',
            'subject_requests:approve',
            'subject_requests:reject',
            'subject_requests:unapprove',
            'student_whitelist:view',
            'student_whitelist:create',
            'student_whitelist:update',
            'student_whitelist:delete',
            'student_whitelist:import',
            'student_whitelist:purge',
            'permissions:view',
            'permissions:manage',
            'assessments:view',
            'assessments:manage',
            'reports:view',
            'reports:export',
            'classrooms:view',
            'classrooms:create',
            'classrooms:update',
            'classrooms:delete',
            'notifications:view',
            'messages:view',
            'messages:create',
            'calendar:view',
            'calendar:create',
            'calendar:update',
            'calendar:delete',
            'announcement:view',
            'announcement:create',
            'announcement:update',
            'announcement:delete',
        ],
    },
    admin: {
        description:
            'Course-scoped academic operator for section delivery, offering workflows, and whitelist management.',
        responsibilities: [
            'Manages sections and operating setup inside the assigned course scope.',
            'Offers and approves subjects only for the courses under direct ownership.',
            'Maintains whitelist records for student accounts at course level.',
        ],
        permissionKeys: [
            'dashboard:view',
            'institutions:view',
            'institutions:manage',
            'departments:view',
            'departments:import',
            'departments:manage',
            'semesters:view',
            'semesters:manage',
            'rooms:view',
            'rooms:create',
            'rooms:update',
            'rooms:delete',
            'rooms:manage',
            'courses:view',
            'subjects:view',
            'users:view',
            'sections:view',
            'sections:create',
            'sections:update',
            'sections:delete',
            'subject_offerings:view',
            'subject_offerings:offer',
            'subject_offerings:approve',
            'subject_offerings:update',
            'subject_requests:view',
            'subject_requests:approve',
            'subject_requests:reject',
            'subject_requests:unapprove',
            'student_whitelist:view',
            'student_whitelist:create',
            'student_whitelist:update',
            'student_whitelist:delete',
            'student_whitelist:import',
            'student_whitelist:purge',
            'permissions:view',
            'permissions:manage',
            'assessments:view',
            'assessments:manage',
            'classrooms:view',
            'classrooms:create',
            'classrooms:update',
            'classrooms:delete',
            'audio_calibration:read',
            'audio_calibration:manage',
            'audio_incidents:read',
            'notifications:view',
            'messages:view',
            'messages:create',
            'calendar:view',
            'calendar:create',
            'calendar:update',
            'calendar:delete',
            'announcement:view',
            'announcement:create',
            'announcement:update',
            'announcement:delete',
            'reports:view',
            'reports:export',
        ],
    },
    proctor: {
        description: 'Live monitoring role for exam sessions, flags, and invigilation workflows.',
        responsibilities: [
            'Monitors examination sessions in real time.',
            'Responds to suspicious activity and handles proctoring flags.',
        ],
        permissionKeys: [
            'dashboard:view',
            'examinations:view',
            'proctoring:view_sessions',
            'proctoring:monitor',
            'proctoring:respond_to_flags',
            'incidents:view',
            'messages:view',
            'messages:create',
            'guides:view',
            'announcement:view',
        ],
    },
    instructor: {
        description: 'Teaching role for viewing assigned academic delivery and learner outcomes.',
        responsibilities: [
            'Reviews subjects and offered-subject coverage relevant to teaching assignments.',
            'Tracks examination access and learner results within owned instruction.',
        ],
        permissionKeys: [
            'dashboard:view',
            'departments:view',
            'semesters:view',
            'subjects:view',
            'subject_offerings:view',
            'subject_requests:view',
            'subject_requests:request',
            'rooms:view',
            'examinations:view',
            'examinations:bypass_publish_lock',
            'audio_incidents:read',
            'assessments:view',
            'assessments:manage',
            'results:view',
            'classrooms:view',
            'classrooms:view_enrolled',
            'notifications:view',
            'messages:view',
            'messages:create',
            'calendar:view',
            'announcement:view',
        ],
    },
    student: {
        description: 'Learner role for exam participation and result review.',
        responsibilities: [
            'Accesses assigned examinations and participation workflows.',
            'Reviews examination outcomes and available guidance.',
        ],
        permissionKeys: [
            'examinations:view',
            'examinations:take',
            'assessments:view',
            'results:view',
            'classrooms:view_enrolled',
            'messages:view',
            'messages:create',
            'guides:view',
            'calendar:view',
            'announcement:view',
        ],
    },
    disciplinary_officer: {
        description:
            'Oversight role for discipline review, incident assessment, and compliance reporting.',
        responsibilities: [
            'Reviews incidents, flags, and discipline-related evidence.',
            'Exports discipline and compliance reports for institutional review.',
        ],
        permissionKeys: [
            'dashboard:view',
            'incidents:view',
            'incidents:review',
            'incidents:export',
            'reports:view',
            'reports:export',
            'messages:view',
            'messages:create',
            'guides:view',
            'announcement:view',
        ],
    },
};

export const SYSTEM_ROLE_ORDER = [
    'support',
    'superadmin',
    'admin',
    'proctor',
    'instructor',
    'disciplinary_officer',
    'student',
] as const;

export const ALL_PERMISSIONS = Object.values(PERMISSIONS);
