export const DEFAULT_TELEMETRY_SETTINGS = {
    version: 1,
    operations: {
        enabled: true,
        ingestionMode: 'sync',
        batchingEnabled: true,
        batchWindowMs: 5000,
        maxBatchSize: 500,
        dedupeWindowSeconds: 120,
    },
    ruleOverrides: {
        'aiRules.gaze_tracking': {},
        'aiRules.face_detection': {},
        'aiRules.audio_anomaly_detection': {},
        'aiRules.multiple_faces_detection': {},
        'webSecurity.tab_switching_monitor': {},
        'webSecurity.full_screen_required': {},
        'webSecurity.clipboard_control': {},
        'webSecurity.right_click_disable': {},
        'webSecurity.print_screen_disable': {},
        'mobileSecurity.app_pinning_required': {},
        'mobileSecurity.prevent_backgrounding': {},
        'mobileSecurity.notification_block': {},
        'mobileSecurity.screenshot_block': {},
        'mobileSecurity.root_jailbreak_detection': {},
    },
    mediaPipeSandbox: {
        enabled: false,
        captureDuringCheckup: false,
        emitDuringExam: false,
        confidenceThreshold: 0.8,
        frameIntervalMs: 500,
        offScreenDurationMs: 3000,
        calibrationRequired: false,
        debugOverlayEnabled: false,
    },
} as const;
