import { type DbClient } from '@sentinel/db';
import {
    type DocumentKind,
    type HeaderConfig,
    type FooterConfig,
    HeaderConfigSchema,
    FooterConfigSchema,
} from '@sentinel/shared/types';
import { randomUUID } from 'crypto';

export interface ResolvedPdfTemplate {
    templateId: string | null;
    documentKind: DocumentKind;
    headerConfig: HeaderConfig;
    footerConfig: FooterConfig;
}

type ResolvePdfTemplateOptions = {
    persistBuiltInFallback?: boolean;
};

// Code-owned built-in defaults
const BUILT_IN_DEFAULTS: Record<
    DocumentKind,
    { headerConfig: HeaderConfig; footerConfig: FooterConfig }
> = {
    ANALYTICS_OVERALL: {
        headerConfig: {
            logo_visible: true,
            logo_placement: 'LEFT',
            logo_max_size_px: 120,
            title_text: 'Sentinel Analytics Report',
            title_alignment: 'LEFT',
            subtitle_text: 'Overall Performance and Incident Summary',
            subtitle_alignment: 'LEFT',
            divider_visible: true,
            divider_color: '#D1D5DB',
            accent_color: '#3B82F6',
            sentinel_logo_visible: true,
        },
        footerConfig: {
            text: 'Generated by Sentinel Assessment Platform',
            confidentiality_label: 'CONFIDENTIAL',
            divider_visible: true,
            divider_color: '#E5E7EB',
            page_number_visible: true,
            page_number_format: 'PAGE_X_OF_Y',
        },
    },
    EXAM_ANSWER_KEY: {
        headerConfig: {
            logo_visible: true,
            logo_placement: 'LEFT',
            logo_max_size_px: 100,
            title_text: 'Examination Answer Key',
            title_alignment: 'CENTER',
            subtitle_text: '',
            subtitle_alignment: 'CENTER',
            divider_visible: true,
            divider_color: '#D1D5DB',
            accent_color: '#10B981',
            sentinel_logo_visible: false,
        },
        footerConfig: {
            text: 'Confidential - For Instructor Use Only',
            confidentiality_label: 'INTERNAL USE ONLY',
            divider_visible: true,
            divider_color: '#E5E7EB',
            page_number_visible: true,
            page_number_format: 'PAGE_X_OF_Y',
        },
    },
};

/**
 * Resolves the active PDF template for a given institution and document kind, applying the precedence rules:
 * 1. Institution-published override.
 * 2. Global-published template.
 * 3. Code-owned built-in default.
 *
 * @param dbClient database client
 * @param institutionId institution ID
 * @param documentKind document kind
 * @returns resolved template details
 */
export async function resolvePdfTemplate(
    dbClient: DbClient,
    institutionId: string | null,
    documentKind: DocumentKind,
    options: ResolvePdfTemplateOptions = {},
): Promise<ResolvedPdfTemplate> {
    // 1. Try to find institution-published override
    if (institutionId) {
        const instOverride = await dbClient
            .selectFrom('pdf_templates')
            .selectAll()
            .where('institution_id', '=', institutionId)
            .where('document_kind', '=', documentKind)
            .where('status', '=', 'PUBLISHED')
            .executeTakeFirst();

        if (instOverride) {
            return {
                templateId: instOverride.template_id,
                documentKind,
                headerConfig: HeaderConfigSchema.parse(instOverride.header_config),
                footerConfig: FooterConfigSchema.parse(instOverride.footer_config),
            };
        }
    }

    // 2. Try to find global-published template
    const globalTemplate = await dbClient
        .selectFrom('pdf_templates')
        .selectAll()
        .where('institution_id', 'is', null)
        .where('document_kind', '=', documentKind)
        .where('status', '=', 'PUBLISHED')
        .executeTakeFirst();

    if (globalTemplate) {
        return {
            templateId: globalTemplate.template_id,
            documentKind,
            headerConfig: HeaderConfigSchema.parse(globalTemplate.header_config),
            footerConfig: FooterConfigSchema.parse(globalTemplate.footer_config),
        };
    }

    // 3. Fall back to built-in defaults
    const builtIn = BUILT_IN_DEFAULTS[documentKind];
    let templateId: string | null = null;

    if (options.persistBuiltInFallback) {
        const persistedFallback = await dbClient
            .selectFrom('pdf_templates')
            .select(['template_id'])
            .where('institution_id', 'is', null)
            .where('document_kind', '=', documentKind)
            .where('status', '=', 'PUBLISHED')
            .executeTakeFirst();

        if (persistedFallback) {
            templateId = persistedFallback.template_id;
        } else {
            templateId = randomUUID();
            const now = new Date();

            await dbClient
                .insertInto('pdf_templates')
                .values({
                    template_id: templateId,
                    institution_id: null,
                    document_kind: documentKind,
                    version: 1,
                    status: 'PUBLISHED',
                    header_config: JSON.stringify(builtIn.headerConfig) as any,
                    footer_config: JSON.stringify(builtIn.footerConfig) as any,
                    created_at: now,
                    updated_at: now,
                    published_at: now,
                })
                .execute();
        }
    }

    return {
        templateId,
        documentKind,
        headerConfig: builtIn.headerConfig,
        footerConfig: builtIn.footerConfig,
    };
}
