import type { QuestionRecord, QuestionTypeDefinition } from '@sentinel/services';
import type { ColumnFiltersState } from '@tanstack/react-table';
import type { ExamQuestion, QuestionType } from '@sentinel/shared/types';
import type { QuestionBuilderPayload } from '@/features/exams/builder/_components/_types';

export type UseQuestionBankPageResult = {
    questions: QuestionRecord[];
    totalQuestions: number;
    pageCount: number;
    pageIndex: number;
    pageSize: number;
    searchQuery: string;
    columnFilters: ColumnFiltersState;
    questionTypes: QuestionTypeDefinition[];
    activeQuestionType: QuestionType | null;
    activeQuestionTypeDefinition?: QuestionTypeDefinition;
    editingQuestion: ExamQuestion | null;
    isQuestionsLoading: boolean;
    isQuestionTypesLoading: boolean;
    isDeletingQuestions: boolean;
    isImportModalOpen: boolean;
    isQuestionBuilderOpen: boolean;
    isTypeSelectorOpen: boolean;
    isDeleteQuestionsDialogOpen: boolean;
    questionsPendingDeletion: QuestionRecord[];
    setIsImportModalOpen: (open: boolean) => void;
    setIsTypeSelectorOpen: (open: boolean) => void;
    setIsDeleteQuestionsDialogOpen: (open: boolean) => void;
    setSearchQuery: (value: string) => void;
    setPagination: (pagination: { pageIndex: number; pageSize: number }) => void;
    setColumnFilters: (filters: ColumnFiltersState) => void;
    handleOpenCreateQuestion: () => void;
    handleSelectQuestionType: (type: QuestionType) => void;
    handleCloseQuestionBuilder: () => void;
    handleCreateQuestion: (payload: QuestionBuilderPayload) => Promise<void>;
    handleUpdateQuestion: (id: string, payload: QuestionBuilderPayload) => Promise<void>;
    handleDuplicateQuestionPayload: (payload: QuestionBuilderPayload) => Promise<void>;
    handleEditQuestion: (question: QuestionRecord) => void;
    handleDuplicateQuestion: (question: QuestionRecord) => Promise<void>;
    handleDeleteQuestion: (question: QuestionRecord) => Promise<void>;
    handleDeleteSelectedQuestions: (questions: QuestionRecord[]) => Promise<void>;
    handleConfirmDeleteQuestions: () => Promise<void>;
};
