ALTER TYPE "public"."notification_resource_type"
ADD VALUE IF NOT EXISTS 'INSTITUTION_ACTIVITY';

ALTER TYPE "public"."notification_action_type"
ADD VALUE IF NOT EXISTS 'INSTITUTION_ACTIVITY_CREATED';

ALTER TYPE "public"."notification_action_type"
ADD VALUE IF NOT EXISTS 'INSTITUTION_ACTIVITY_UPDATED';

ALTER TYPE "public"."notification_action_type"
ADD VALUE IF NOT EXISTS 'INSTITUTION_ACTIVITY_DELETED';

ALTER TYPE "public"."notification_action_type"
ADD VALUE IF NOT EXISTS 'INSTITUTION_ACTIVITY_TRANSACTION_COMPLETED';

ALTER TYPE "public"."notification_action_type"
ADD VALUE IF NOT EXISTS 'INSTITUTION_ACTIVITY_OVERRIDE_COMPLETED';
