import PDFDocument from 'pdfkit';
import { PDF_LAYOUT } from './pdf-page-layout';
import { AnalyticsOverallData, normalizeAnalyticsOverallData } from './analytics-overall-view-model';
import { renderPdfDocumentBuffer } from './render-pdf-buffer';
import { HeaderConfig } from './pdf-header-renderer';
import { FooterConfig } from './pdf-footer-renderer';

/**
 * Draws a section header with accent line and text.
 */
function drawSectionHeader(doc: typeof PDFDocument, title: string, y: number): number {
    doc.save();
    doc.fillColor(PDF_LAYOUT.colors.sentinelPrimary)
        .rect(PDF_LAYOUT.marginLeft, y, 4, 15)
        .fill();

    doc.fillColor(PDF_LAYOUT.colors.textPrimary)
        .font(PDF_LAYOUT.fonts.bold)
        .fontSize(11)
        .text(title, PDF_LAYOUT.marginLeft + 10, y + 2);

    doc.restore();
    return y + 25;
}

/**
 * Checks if a section requires a page break.
 */
function checkPageBreak(doc: typeof PDFDocument, currentY: number, heightNeeded: number): number {
    if (currentY + heightNeeded > PDF_LAYOUT.pageHeight - PDF_LAYOUT.marginBottom) {
        doc.addPage();
        return PDF_LAYOUT.marginTop;
    }
    return currentY;
}

/**
 * Draws the body content of the Overall Analytics PDF report.
 * 
 * @param doc PDFKit document
 * @param data normalized view model data
 */
export function drawAnalyticsOverallBody(doc: typeof PDFDocument, data: AnalyticsOverallData): void {
    let y = PDF_LAYOUT.marginTop;

    // 1. Report Metadata Card
    doc.save();
    doc.rect(PDF_LAYOUT.marginLeft, y, PDF_LAYOUT.pageWidth - PDF_LAYOUT.marginLeft - PDF_LAYOUT.marginRight, 50)
        .fillColor('#F9FAFB')
        .fill();
    doc.rect(PDF_LAYOUT.marginLeft, y, PDF_LAYOUT.pageWidth - PDF_LAYOUT.marginLeft - PDF_LAYOUT.marginRight, 50)
        .strokeColor(PDF_LAYOUT.colors.border)
        .lineWidth(0.5)
        .stroke();

    doc.fillColor(PDF_LAYOUT.colors.textSecondary)
        .font(PDF_LAYOUT.fonts.regular)
        .fontSize(8);

    doc.text(`Institution: ${data.institutionName}`, PDF_LAYOUT.marginLeft + 12, y + 10);
    doc.text(`Generated By: ${data.generatedBy}`, PDF_LAYOUT.marginLeft + 12, y + 22);
    doc.text(`Period: ${data.periodLabel}`, PDF_LAYOUT.marginLeft + 12, y + 34);

    const generatedDateStr = new Date(data.generatedAt).toLocaleString('en-US', { timeZone: 'Asia/Manila' });
    doc.text(`Generated At: ${generatedDateStr} (PHT)`, PDF_LAYOUT.pageWidth - PDF_LAYOUT.marginRight - 220, y + 10, {
        width: 200,
        align: 'right'
    });
    doc.restore();
    y += 70;

    // 2. KPI Score Cards Grid (2x2 layout)
    y = drawSectionHeader(doc, 'KEY PERFORMANCE INDICATORS', y);

    const cardWidth = (PDF_LAYOUT.pageWidth - PDF_LAYOUT.marginLeft - PDF_LAYOUT.marginRight - 15) / 2;
    const cardHeight = 45;

    const kpiCards = [
        { label: 'Average Exam Score', value: `${data.kpis.averageScore}%`, color: PDF_LAYOUT.colors.sentinelPrimary },
        { label: 'Overall Pass Rate', value: `${data.kpis.passRate}%`, color: '#10B981' }, // green
        { label: 'Total Completed Exams', value: data.kpis.totalCompletions.toLocaleString(), color: '#6366F1' }, // indigo
        { label: 'Integrity Incidents Flagged', value: data.kpis.integrityIncidentsCount.toLocaleString(), color: '#EF4444' } // red
    ];

    doc.save();
    kpiCards.forEach((kpi, idx) => {
        const row = Math.floor(idx / 2);
        const col = idx % 2;
        const cardX = PDF_LAYOUT.marginLeft + col * (cardWidth + 15);
        const cardY = y + row * (cardHeight + 12);

        // Background
        doc.rect(cardX, cardY, cardWidth, cardHeight)
            .fillColor('#F3F4F6')
            .fill();

        // Border line on left
        doc.rect(cardX, cardY, 4, cardHeight)
            .fillColor(kpi.color)
            .fill();

        // Value text
        doc.fillColor(PDF_LAYOUT.colors.textPrimary)
            .font(PDF_LAYOUT.fonts.bold)
            .fontSize(16)
            .text(kpi.value, cardX + 12, cardY + 8);

        // Label text
        doc.fillColor(PDF_LAYOUT.colors.textSecondary)
            .font(PDF_LAYOUT.fonts.regular)
            .fontSize(8)
            .text(kpi.label, cardX + 12, cardY + 26);
    });
    doc.restore();
    y += 120;

    // 3. Department Performance Table
    y = checkPageBreak(doc, y, 150);
    y = drawSectionHeader(doc, 'DEPARTMENT & SUBJECT PERFORMANCE', y);

    const cols = [
        { name: 'Department', width: 180, align: 'left' },
        { name: 'Courses', width: 60, align: 'center' },
        { name: 'Students', width: 60, align: 'center' },
        { name: 'Avg Score', width: 80, align: 'right' },
        { name: 'Integrity Rate', width: 100, align: 'right' }
    ] as const;

    // Draw Table Header
    doc.save();
    doc.rect(PDF_LAYOUT.marginLeft, y, PDF_LAYOUT.pageWidth - PDF_LAYOUT.marginLeft - PDF_LAYOUT.marginRight, 20)
        .fillColor('#374151') // dark gray
        .fill();

    let curX = PDF_LAYOUT.marginLeft;
    doc.fillColor('#FFFFFF')
        .font(PDF_LAYOUT.fonts.bold)
        .fontSize(8);

    cols.forEach(col => {
        const align = col.align;
        const padding = align === 'left' ? 8 : align === 'right' ? -8 : 0;
        doc.text(col.name, curX + padding, y + 6, {
            width: col.width,
            align
        });
        curX += col.width;
    });
    doc.restore();
    y += 20;

    // Draw Rows
    doc.save();
    doc.font(PDF_LAYOUT.fonts.regular)
        .fontSize(8);

    data.departments.forEach((dept, idx) => {
        y = checkPageBreak(doc, y, 20);

        // Alternating row background
        if (idx % 2 === 1) {
            doc.rect(PDF_LAYOUT.marginLeft, y, PDF_LAYOUT.pageWidth - PDF_LAYOUT.marginLeft - PDF_LAYOUT.marginRight, 18)
                .fillColor('#F9FAFB')
                .fill();
        }

        // Draw Row Border bottom
        doc.moveTo(PDF_LAYOUT.marginLeft, y + 18)
            .lineTo(PDF_LAYOUT.pageWidth - PDF_LAYOUT.marginRight, y + 18)
            .strokeColor(PDF_LAYOUT.colors.border)
            .lineWidth(0.5)
            .stroke();

        let rowX = PDF_LAYOUT.marginLeft;
        doc.fillColor(PDF_LAYOUT.colors.textPrimary);

        // Department Name
        doc.text(dept.departmentName, rowX + 8, y + 5, { width: cols[0].width, lineBreak: false });
        rowX += cols[0].width;

        // Courses Count
        doc.text(dept.courseCount.toString(), rowX, y + 5, { width: cols[1].width, align: 'center' });
        rowX += cols[1].width;

        // Students Count
        doc.text(dept.studentCount.toString(), rowX, y + 5, { width: cols[2].width, align: 'center' });
        rowX += cols[2].width;

        // Average Score
        doc.text(`${dept.averageScore}%`, rowX - 8, y + 5, { width: cols[3].width, align: 'right' });
        rowX += cols[3].width;

        // Integrity Rate
        doc.text(`${dept.integrityRate}%`, rowX - 8, y + 5, { width: cols[4].width, align: 'right' });

        y += 18;
    });
    doc.restore();
    y += 20;

    // 4. Integrity Incident Breakdown
    y = checkPageBreak(doc, y, 140);
    y = drawSectionHeader(doc, 'INTEGRITY INCIDENT METRICS', y);

    const halfWidth = (PDF_LAYOUT.pageWidth - PDF_LAYOUT.marginLeft - PDF_LAYOUT.marginRight - 20) / 2;
    let incidentY = y;

    // Left Column: Incidents by Severity
    doc.save();
    doc.font(PDF_LAYOUT.fonts.bold)
        .fontSize(9)
        .fillColor(PDF_LAYOUT.colors.textPrimary)
        .text('Incidents by Severity', PDF_LAYOUT.marginLeft, incidentY);

    incidentY += 15;
    data.incidentSeverities.forEach(s => {
        let barColor = '#EF4444'; // Red for high
        if (s.severity === 'LOW') barColor = '#3B82F6'; // Blue
        if (s.severity === 'MEDIUM') barColor = '#F59E0B'; // Orange

        doc.fillColor(PDF_LAYOUT.colors.textSecondary)
            .font(PDF_LAYOUT.fonts.regular)
            .fontSize(8)
            .text(`${s.severity}: ${s.count}`, PDF_LAYOUT.marginLeft, incidentY);

        // Simple horizontal bar chart representing count proportion
        const maxBarWidth = halfWidth - 100;
        const barWidth = Math.min(s.count * 15, maxBarWidth) || 4;

        doc.rect(PDF_LAYOUT.marginLeft + 80, incidentY - 1, barWidth, 7)
            .fillColor(barColor)
            .fill();

        incidentY += 16;
    });
    doc.restore();

    // Right Column: Incidents by Type
    let typeY = y;
    doc.save();
    doc.font(PDF_LAYOUT.fonts.bold)
        .fontSize(9)
        .fillColor(PDF_LAYOUT.colors.textPrimary)
        .text('Incidents by Type', PDF_LAYOUT.marginLeft + halfWidth + 20, typeY);

    typeY += 15;
    if (data.incidentTypes.length === 0) {
        doc.font(PDF_LAYOUT.fonts.regular)
            .fontSize(8)
            .fillColor(PDF_LAYOUT.colors.textLight)
            .text('No incidents recorded.', PDF_LAYOUT.marginLeft + halfWidth + 20, typeY);
    } else {
        data.incidentTypes.slice(0, 5).forEach(t => {
            doc.fillColor(PDF_LAYOUT.colors.textSecondary)
                .font(PDF_LAYOUT.fonts.regular)
                .fontSize(8)
                .text(`${t.type}`, PDF_LAYOUT.marginLeft + halfWidth + 20, typeY, { width: 120, lineBreak: false });

            doc.text(`${t.count} (${t.percentage}%)`, PDF_LAYOUT.pageWidth - PDF_LAYOUT.marginRight - 70, typeY, {
                width: 70,
                align: 'right'
            });

            typeY += 16;
        });
    }
    doc.restore();
}

/**
 * Renders an Overall Analytics PDF report using the configured templates and branding data.
 * 
 * @param headerConfig header layout parameters
 * @param footerConfig footer layout parameters
 * @param logoBuffer optional PNG buffer of the institution logo
 * @param rawData raw or partial analytics metrics
 * @returns binary PDF document buffer
 */
export async function renderAnalyticsOverallPdf(
    headerConfig: HeaderConfig,
    footerConfig: FooterConfig,
    logoBuffer: Buffer | null,
    rawData: Partial<AnalyticsOverallData>
): Promise<Buffer> {
    const data = normalizeAnalyticsOverallData(rawData);

    return await renderPdfDocumentBuffer(
        headerConfig,
        footerConfig,
        logoBuffer,
        (doc) => {
            drawAnalyticsOverallBody(doc, data);
        }
    );
}
