import PDFDocument from 'pdfkit';
import { PDF_LAYOUT } from './pdf-page-layout';
import {
    ExamAnswerKeyData,
    QuestionViewModel,
    normalizeExamAnswerKeyData,
} from './exam-answer-key-view-model';
import { parsePassageToPdfBlocks, PdfTextRun } from './safe-passage-to-pdf-blocks';
import { renderPdfDocumentBuffer } from './render-pdf-buffer';
import { HeaderConfig } from './pdf-header-renderer';
import { FooterConfig } from './pdf-footer-renderer';

/**
 * Checks if a section requires a page break.
 */
function checkPageBreak(doc: typeof PDFDocument, currentY: number, heightNeeded: number): number {
    if (currentY + heightNeeded > PDF_LAYOUT.pageHeight - PDF_LAYOUT.marginBottom) {
        doc.addPage();
        return PDF_LAYOUT.marginTop;
    }
    return currentY;
}

/**
 * Draws inline formatted text runs using PDFKit continued blocks.
 */
function drawTextRuns(
    doc: typeof PDFDocument,
    runs: PdfTextRun[],
    startX: number,
    startY: number,
    width: number,
): number {
    doc.x = startX;
    doc.y = startY;

    runs.forEach((run, idx) => {
        const isLast = idx === runs.length - 1;
        const fontName = run.bold
            ? PDF_LAYOUT.fonts.bold
            : run.italic
              ? PDF_LAYOUT.fonts.oblique
              : PDF_LAYOUT.fonts.regular;

        doc.font(fontName);
        doc.text(run.text, {
            continued: !isLast,
            width: width,
        });
    });

    return doc.y + doc.currentLineHeight();
}

/**
 * Parses and draws HTML/plain text strings onto the PDF.
 */
function drawStyledText(
    doc: typeof PDFDocument,
    text: string,
    x: number,
    y: number,
    width: number,
): number {
    const blocks = parsePassageToPdfBlocks(text);
    let curY = y;

    blocks.forEach((block) => {
        curY = checkPageBreak(doc, curY, 20);
        if (block.type === 'break') {
            curY += 8;
            return;
        }

        let startX = x;
        let blockWidth = width;
        if (block.type === 'bullet') {
            doc.font(PDF_LAYOUT.fonts.regular).fontSize(9);
            doc.text('•', x, curY);
            startX = x + 10;
            blockWidth = width - 10;
        } else if (block.type === 'heading') {
            doc.font(PDF_LAYOUT.fonts.bold).fontSize(10);
        } else {
            doc.font(PDF_LAYOUT.fonts.regular).fontSize(9);
        }

        if (block.runs.length > 0) {
            curY = drawTextRuns(doc, block.runs, startX, curY, blockWidth) + 4;
        } else {
            curY += doc.currentLineHeight() + 4;
        }
    });

    return curY;
}

/**
 * Draws the body content of the Exam Answer Key PDF export.
 */
export function drawExamAnswerKeyBody(doc: typeof PDFDocument, data: ExamAnswerKeyData): void {
    let y = PDF_LAYOUT.marginTop;

    // 1. Title Page Header / Metadata Card
    doc.save();
    doc.rect(
        PDF_LAYOUT.marginLeft,
        y,
        PDF_LAYOUT.pageWidth - PDF_LAYOUT.marginLeft - PDF_LAYOUT.marginRight,
        60,
    )
        .fillColor('#F9FAFB')
        .fill();
    doc.rect(
        PDF_LAYOUT.marginLeft,
        y,
        PDF_LAYOUT.pageWidth - PDF_LAYOUT.marginLeft - PDF_LAYOUT.marginRight,
        60,
    )
        .strokeColor(PDF_LAYOUT.colors.border)
        .lineWidth(0.5)
        .stroke();

    doc.fillColor(PDF_LAYOUT.colors.textPrimary)
        .font(PDF_LAYOUT.fonts.bold)
        .fontSize(11)
        .text(data.title, PDF_LAYOUT.marginLeft + 12, y + 10);

    doc.fillColor(PDF_LAYOUT.colors.textSecondary).font(PDF_LAYOUT.fonts.regular).fontSize(8);

    doc.text(
        `Subject: ${data.subjectCode} - ${data.subjectName}`,
        PDF_LAYOUT.marginLeft + 12,
        y + 25,
    );
    doc.text(
        `Difficulty: ${data.difficulty}   |   Passing Score: ${data.passingScore}%   |   Duration: ${data.durationMinutes} mins`,
        PDF_LAYOUT.marginLeft + 12,
        y + 37,
    );

    const generatedDateStr = new Date(data.generatedAt).toLocaleString('en-US', {
        timeZone: 'Asia/Manila',
    });
    doc.text(
        `Generated By: ${data.generatedBy}`,
        PDF_LAYOUT.pageWidth - PDF_LAYOUT.marginRight - 200,
        y + 25,
        { width: 180, align: 'right' },
    );
    doc.text(
        `Generated At: ${generatedDateStr} (PHT)`,
        PDF_LAYOUT.pageWidth - PDF_LAYOUT.marginRight - 200,
        y + 37,
        { width: 180, align: 'right' },
    );

    doc.restore();
    y += 75;

    // 2. Loop and Draw Questions
    let lastPassageText = '';
    const bodyWidth = PDF_LAYOUT.pageWidth - PDF_LAYOUT.marginLeft - PDF_LAYOUT.marginRight;

    data.questions.forEach((q, idx) => {
        // Reserve height for question header
        y = checkPageBreak(doc, y, 40);

        // A. Draw passage if present and new
        if (q.passageText && q.passageText.trim() !== lastPassageText) {
            lastPassageText = q.passageText.trim();
            y = checkPageBreak(doc, y, 60);

            doc.save();
            doc.font(PDF_LAYOUT.fonts.bold).fontSize(8).fillColor(PDF_LAYOUT.colors.textSecondary);
            doc.text('READING PASSAGE:', PDF_LAYOUT.marginLeft, y);
            y += 12;

            // Draw passage in a box
            const passageBoxY = y;
            const tempY = drawStyledText(
                doc,
                q.passageText,
                PDF_LAYOUT.marginLeft + 10,
                y + 8,
                bodyWidth - 20,
            );
            const boxHeight = tempY - passageBoxY + 8;

            doc.rect(PDF_LAYOUT.marginLeft, passageBoxY, bodyWidth, boxHeight)
                .strokeColor('#D1D5DB')
                .lineWidth(0.5)
                .stroke();
            doc.restore();
            y = tempY + 15;
        }

        // B. Draw Question Number and Text
        doc.save();
        doc.font(PDF_LAYOUT.fonts.bold).fontSize(10).fillColor(PDF_LAYOUT.colors.sentinelPrimary);

        doc.text(`Question ${idx + 1}`, PDF_LAYOUT.marginLeft, y);
        doc.font(PDF_LAYOUT.fonts.regular)
            .fontSize(8)
            .fillColor(PDF_LAYOUT.colors.textLight)
            .text(`(${q.points} pt)`, PDF_LAYOUT.marginLeft + 70, y + 2);

        y += 15;
        doc.restore();

        // Draw HTML or plain text question
        y = drawStyledText(doc, q.text, PDF_LAYOUT.marginLeft, y, bodyWidth) + 6;

        // C. Draw Image placeholder if present
        if (q.imageUrl) {
            y = checkPageBreak(doc, y, 50);
            doc.save();
            doc.rect(PDF_LAYOUT.marginLeft, y, 150, 40).fillColor('#F3F4F6').fill();
            doc.rect(PDF_LAYOUT.marginLeft, y, 150, 40)
                .strokeColor(PDF_LAYOUT.colors.border)
                .stroke();
            doc.fontSize(7)
                .fillColor(PDF_LAYOUT.colors.textSecondary)
                .font(PDF_LAYOUT.fonts.regular)
                .text('[Associated Exam Figure / Image]', PDF_LAYOUT.marginLeft + 10, y + 16, {
                    width: 130,
                    align: 'center',
                });
            doc.restore();
            y += 48;
        }

        // D. Draw Answer format depending on QuestionType
        y = checkPageBreak(doc, y, 30);

        switch (q.type) {
            case 'MULTIPLE_CHOICE':
            case 'MULTIPLE_SELECT': {
                const isMS = q.type === 'MULTIPLE_SELECT';
                (q.options || []).forEach((opt, oIdx) => {
                    y = checkPageBreak(doc, y, 15);
                    const letter = String.fromCharCode(65 + oIdx); // A, B, C, D

                    doc.save();
                    if (opt.isCorrect) {
                        doc.fillColor('#10B981') // Green for correct
                            .font(PDF_LAYOUT.fonts.bold);
                        doc.text(`[✓] ${letter}. ${opt.optionText}`, PDF_LAYOUT.marginLeft + 15, y);
                    } else {
                        doc.fillColor(PDF_LAYOUT.colors.textSecondary);
                        doc.text(`[ ] ${letter}. ${opt.optionText}`, PDF_LAYOUT.marginLeft + 15, y);
                    }
                    doc.restore();
                    y += 14;
                });
                break;
            }
            case 'TRUE_FALSE': {
                y = checkPageBreak(doc, y, 15);
                const isTrue = q.trueFalseAnswer === true;

                doc.save();
                doc.font(PDF_LAYOUT.fonts.bold);
                if (isTrue) {
                    doc.fillColor('#10B981').text('[✓] True', PDF_LAYOUT.marginLeft + 15, y);
                    doc.fillColor(PDF_LAYOUT.colors.textSecondary)
                        .font(PDF_LAYOUT.fonts.regular)
                        .text('[ ] False', PDF_LAYOUT.marginLeft + 15, y + 14);
                } else {
                    doc.fillColor(PDF_LAYOUT.colors.textSecondary)
                        .font(PDF_LAYOUT.fonts.regular)
                        .text('[ ] True', PDF_LAYOUT.marginLeft + 15, y);
                    doc.fillColor('#10B981').text('[✓] False', PDF_LAYOUT.marginLeft + 15, y + 14);
                }
                doc.restore();
                y += 28;
                break;
            }
            case 'SHORT_ANSWER': {
                doc.save();
                doc.rect(PDF_LAYOUT.marginLeft + 15, y, bodyWidth - 30, 20)
                    .fillColor('#ECFDF5') // Light green bg
                    .fill();
                doc.rect(PDF_LAYOUT.marginLeft + 15, y, bodyWidth - 30, 20)
                    .strokeColor('#10B981')
                    .lineWidth(0.5)
                    .stroke();

                doc.fillColor('#065F46')
                    .font(PDF_LAYOUT.fonts.bold)
                    .fontSize(8)
                    .text(
                        `Correct Pattern: ${q.shortAnswerPattern || 'No correct pattern defined.'}`,
                        PDF_LAYOUT.marginLeft + 25,
                        y + 6,
                    );
                doc.restore();
                y += 26;
                break;
            }
            case 'ESSAY': {
                doc.save();
                doc.font(PDF_LAYOUT.fonts.bold)
                    .fontSize(8)
                    .fillColor(PDF_LAYOUT.colors.textPrimary);
                doc.text('Grading Rubric:', PDF_LAYOUT.marginLeft + 15, y);
                y += 12;

                const rubricItems = q.rubric || [];
                if (rubricItems.length === 0) {
                    doc.font(PDF_LAYOUT.fonts.regular).fillColor(PDF_LAYOUT.colors.textLight);
                    doc.text(
                        'No evaluation rubric defined for this essay question.',
                        PDF_LAYOUT.marginLeft + 15,
                        y,
                    );
                    y += 14;
                } else {
                    rubricItems.forEach((rub) => {
                        y = checkPageBreak(doc, y, 20);
                        doc.fillColor(PDF_LAYOUT.colors.textPrimary)
                            .font(PDF_LAYOUT.fonts.bold)
                            .text(
                                `${rub.criterion} (${rub.maxPoints} pts)`,
                                PDF_LAYOUT.marginLeft + 25,
                                y,
                            );

                        if (rub.description) {
                            y += 11;
                            y = checkPageBreak(doc, y, 20);
                            doc.fillColor(PDF_LAYOUT.colors.textSecondary)
                                .font(PDF_LAYOUT.fonts.regular)
                                .text(rub.description, PDF_LAYOUT.marginLeft + 25, y, {
                                    width: bodyWidth - 50,
                                });
                        }
                        y += 16;
                    });
                }
                doc.restore();
                break;
            }
            case 'FILL_IN_BLANK': {
                doc.save();
                doc.fillColor(PDF_LAYOUT.colors.textPrimary)
                    .font(PDF_LAYOUT.fonts.bold)
                    .text('Correct Blank Values:', PDF_LAYOUT.marginLeft + 15, y);
                y += 12;

                (q.blankAnswers || []).forEach((blank, bIdx) => {
                    y = checkPageBreak(doc, y, 15);
                    doc.fillColor(PDF_LAYOUT.colors.textSecondary)
                        .font(PDF_LAYOUT.fonts.regular)
                        .text(`Blank [${bIdx + 1}]: `, PDF_LAYOUT.marginLeft + 25, y, {
                            continued: true,
                        })
                        .fillColor('#065F46')
                        .font(PDF_LAYOUT.fonts.bold)
                        .text(blank);
                    y += 14;
                });
                doc.restore();
                break;
            }
            case 'MATCHING': {
                doc.save();
                doc.fillColor(PDF_LAYOUT.colors.textPrimary)
                    .font(PDF_LAYOUT.fonts.bold)
                    .text('Correct Associations:', PDF_LAYOUT.marginLeft + 15, y);
                y += 12;

                (q.matchingPairs || []).forEach((pair) => {
                    y = checkPageBreak(doc, y, 15);
                    doc.fillColor(PDF_LAYOUT.colors.textSecondary)
                        .font(PDF_LAYOUT.fonts.regular)
                        .text(`"${pair.premise}"`, PDF_LAYOUT.marginLeft + 25, y, {
                            continued: true,
                        })
                        .font(PDF_LAYOUT.fonts.bold)
                        .fillColor(PDF_LAYOUT.colors.sentinelPrimary)
                        .text('  matches with  ', { continued: true })
                        .fillColor('#065F46')
                        .font(PDF_LAYOUT.fonts.bold)
                        .text(`"${pair.response}"`);
                    y += 14;
                });
                doc.restore();
                break;
            }
            case 'ORDERING': {
                doc.save();
                doc.fillColor(PDF_LAYOUT.colors.textPrimary)
                    .font(PDF_LAYOUT.fonts.bold)
                    .text('Correct Sequence:', PDF_LAYOUT.marginLeft + 15, y);
                y += 12;

                (q.orderedItems || []).forEach((item, oIdx) => {
                    y = checkPageBreak(doc, y, 15);
                    doc.fillColor(PDF_LAYOUT.colors.textSecondary)
                        .font(PDF_LAYOUT.fonts.regular)
                        .text(`${oIdx + 1}. `, PDF_LAYOUT.marginLeft + 25, y, { continued: true })
                        .font(PDF_LAYOUT.fonts.bold)
                        .fillColor(PDF_LAYOUT.colors.textPrimary)
                        .text(item);
                    y += 14;
                });
                doc.restore();
                break;
            }
        }

        y += 20; // Margin after question
    });
}

/**
 * Renders an Exam Answer Key PDF document using the configured templates and branding data.
 */
export async function renderExamAnswerKeyPdf(
    headerConfig: HeaderConfig,
    footerConfig: FooterConfig,
    logoBuffer: Buffer | null,
    rawData: Partial<ExamAnswerKeyData>,
): Promise<Buffer> {
    const data = normalizeExamAnswerKeyData(rawData);

    return await renderPdfDocumentBuffer(headerConfig, footerConfig, logoBuffer, (doc) => {
        drawExamAnswerKeyBody(doc, data);
    });
}
