import { Dimensions, StyleSheet } from 'react-native';
import { Colors } from '@/constants/theme';

const { width, height } = Dimensions.get('window');

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Colors.light.background,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingTop: 12,
        paddingBottom: 20,
        backgroundColor: Colors.light.background,
    },
    backButton: {
        width: 44,
        height: 44,
        borderRadius: 12,
        backgroundColor: Colors.light.input,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 16,
    },
    headerTitle: {
        fontSize: width < 380 ? 20 : 24,
        fontWeight: '800',
        color: Colors.light.text,
        letterSpacing: -0.5,
    },
    content: {
        paddingHorizontal: 24,
        paddingTop: 8,
        paddingBottom: 40,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: Colors.light.text,
        marginTop: 24,
        marginBottom: 16,
    },
    label: {
        fontSize: 14,
        fontWeight: '600',
        color: Colors.light.text,
        marginBottom: 8,
        opacity: 0.8,
    },
    dropdown: {
        minHeight: 56,
        backgroundColor: Colors.light.input,
        borderRadius: 16,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderWidth: 1,
        borderColor: Colors.light.border,
        marginBottom: 20,
        gap: 12,
    },
    dropdownDisabled: {
        opacity: 0.5,
        backgroundColor: Colors.light.background,
    },
    inputContainer: {
        height: 56,
        backgroundColor: Colors.light.input,
        borderRadius: 16,
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        borderWidth: 1,
        borderColor: Colors.light.border,
        marginBottom: 20,
    },
    input: {
        flex: 1,
        fontSize: 16,
        color: Colors.light.text,
        fontWeight: '500',
    },
    inputText: {
        flex: 1,
        fontSize: 16,
        color: Colors.light.text,
        fontWeight: '500',
    },
    placeholderText: {
        flex: 1,
        fontSize: 16,
        color: Colors.light.icon,
    },
    alert: {
        backgroundColor: Colors.light.primary + '10',
        padding: 16,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: Colors.light.primary + '20',
        marginBottom: 24,
        flexDirection: 'row',
        gap: 12,
    },
    alertTitle: {
        fontSize: 15,
        fontWeight: '700',
        color: Colors.light.primary,
        marginBottom: 4,
    },
    alertDescription: {
        fontSize: 13,
        color: Colors.light.text,
        lineHeight: 18,
        opacity: 0.7,
        flex: 1,
    },
    footer: {
        padding: 24,
        paddingBottom: height < 700 ? 24 : 40,
        backgroundColor: Colors.light.background,
        borderTopLeftRadius: 32,
        borderTopRightRadius: 32,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -10 },
        shadowOpacity: 0.08,
        shadowRadius: 15,
        elevation: 20,
    },
    button: {
        backgroundColor: Colors.light.primary,
        height: 56,
        borderRadius: 18,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: Colors.light.primary,
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.25,
        shadowRadius: 10,
        elevation: 6,
    },
    buttonDisabled: {
        backgroundColor: Colors.light.border,
        shadowOpacity: 0,
        elevation: 0,
    },
    buttonText: {
        color: '#fff',
        fontSize: 18,
        fontWeight: '700',
    },
    // Modal Styles
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'flex-end',
    },
    modalContent: {
        backgroundColor: Colors.light.background,
        borderTopLeftRadius: 32,
        borderTopRightRadius: 32,
        maxHeight: '85%',
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 24,
        paddingBottom: 16,
    },
    modalTitle: {
        fontSize: 24,
        fontWeight: '800',
        color: Colors.light.text,
        letterSpacing: -0.5,
    },
    closeButtonText: {
        fontSize: 16,
        color: Colors.light.primary,
        fontWeight: '700',
    },
    modalItem: {
        paddingVertical: 18,
        paddingHorizontal: 24,
        borderBottomWidth: 1,
        borderBottomColor: Colors.light.input,
    },
    modalItemText: {
        fontSize: 16,
        color: Colors.light.text,
        fontWeight: '600',
    },
    modalItemSubtext: {
        fontSize: 13,
        color: Colors.light.text,
        opacity: 0.5,
        marginTop: 2,
    },
    searchContainer: {
        backgroundColor: Colors.light.input,
        marginHorizontal: 24,
        marginBottom: 16,
        borderRadius: 16,
        paddingHorizontal: 16,
        height: 52,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
    },
    searchInput: {
        fontSize: 16,
        color: Colors.light.text,
        flex: 1,
        height: '100%',
    },
    emptyContainer: {
        padding: 48,
        alignItems: 'center',
    },
    emptyText: {
        color: Colors.light.icon,
        fontSize: 16,
        fontWeight: '500',
    },
});

export default styles;
