ALTER TYPE "public"."notification_resource_type"
ADD VALUE IF NOT EXISTS 'SUBJECT_ENROLLMENT_REQUEST';

ALTER TYPE "public"."notification_action_type"
ADD VALUE IF NOT EXISTS 'SUBJECT_ENROLLMENT_REQUEST_SUBMITTED';

ALTER TYPE "public"."notification_action_type"
ADD VALUE IF NOT EXISTS 'SUBJECT_ENROLLMENT_REQUEST_APPROVED';

ALTER TYPE "public"."notification_action_type"
ADD VALUE IF NOT EXISTS 'SUBJECT_ENROLLMENT_REQUEST_REJECTED';
