import { PERMISSION_CATEGORIES } from '@sentinel/shared/constants';

export const FORMAL_ROLE_LABELS: Record<string, string> = {
    support: 'Support',
    superadmin: 'Superadmin',
    admin: 'Admin',
    proctor: 'Proctor',
    instructor: 'Instructor',
    student: 'Student',
    disciplinary_officer: 'Disciplinary Officer',
};

export const CATEGORY_SORT_ORDER = Object.keys(PERMISSION_CATEGORIES);

export const ACTION_SORT_ORDER = [
    'view',
    'create',
    'update',
    'delete',
    'offer',
    'request',
    'approve',
    'reject',
    'unapprove',
    'import',
    'purge',
    'publish',
    'take',
    'review',
    'export',
    'monitor',
    'respond_to_flags',
    'view_sessions',
    'create_superadmin',
    'create_admin',
    'create_staff',
    'create_student',
    'manage_roles',
    'manage_permissions',
    'manage_assignments',
] as const;

export const MODULE_SORT_ORDER = [
    'institutions',
    'departments',
    'semesters',
    'rooms',
    'users',
    'access_control',
    'courses',
    'sections',
    'subjects',
    'subject_offerings',
    'subject_requests',
    'student_whitelist',
    'examination_settings',
    'examinations',
    'results',
    'proctoring',
    'incidents',
    'reports',
    'guides',
    'dashboard',
] as const;

export const SYSTEM_AREAS = [
    {
        key: 'core',
        title: 'Core Modules',
        description: 'Academic and institutional modules from the core backend area.',
        sourcePath: 'app/sentinel-api/src/modules/core',
        moduleKeys: [
            'institutions',
            'departments',
            'semesters',
            'rooms',
            'courses',
            'sections',
            'subjects',
            'subject_offerings',
        ],
    },
    {
        key: 'identity',
        title: 'Identity Modules',
        description: 'Account, whitelist, and request modules from the identity backend area.',
        sourcePath: 'app/sentinel-api/src/modules/identity',
        moduleKeys: ['users', 'subject_requests', 'student_whitelist'],
    },
    {
        key: 'security',
        title: 'Security Modules',
        description: 'RBAC and control modules from the security backend area.',
        sourcePath: 'app/sentinel-api/src/modules/security',
        moduleKeys: ['access_control'],
    },
    {
        key: 'examination',
        title: 'Examination Modules',
        description: 'Assessment and examination-related controls.',
        sourcePath: 'app/sentinel-api/src/modules/examination',
        moduleKeys: ['examination_settings', 'examinations', 'results'],
    },
    {
        key: 'operations',
        title: 'Operational Modules',
        description: 'Monitoring, reporting, guidance, and platform visibility modules.',
        sourcePath: 'cross-module platform services',
        moduleKeys: ['proctoring', 'incidents', 'reports', 'guides', 'dashboard'],
    },
];
