export const LIVEKIT_REQUEST_TIMEOUT_MS = 20_000;
export const LIVEKIT_VIEWER_JOIN_TIMEOUT_MS = 15_000;
export const LIVEKIT_MAX_INSPECTION_DURATION_SECONDS = 300;
export const LIVEKIT_TOKEN_TTL_SECONDS = 60;
export const LIVEKIT_ROOM_EMPTY_TIMEOUT_SECONDS = 30;
export const LIVEKIT_ROOM_DEPARTURE_TIMEOUT_SECONDS = 10;
export const LIVEKIT_GLOBAL_ACTIVE_INSPECTION_LIMIT = 20;
export const LIVEKIT_INSTITUTION_ACTIVE_INSPECTION_LIMIT = 10;
