import type { Exam } from '../_types/exam';
import { mockQuestions } from './questions';

export const mockExams: Exam[] = [
    {
        id: 'exam-001',
        title: 'Advanced Web Development Midterm',
        description: 'Covers React, Next.js, and modern CSS techniques.',
        timeLimit: 60,
        passingScore: 75,
        status: 'published',
        subject: 'Web Development',
        duration: 60,
        studentsCount: 45,
        questionCount: 30,
        scheduledDate: '2026-03-25T10:00:00Z',
        settings: {
            shuffleQuestions: true,
            showCorrectAnswers: false,
            allowReview: true,
            randomizeChoices: true,
        },
        questions: mockQuestions.slice(0, 3),
        createdAt: '2026-03-01T10:00:00Z',
        updatedAt: '2026-03-15T14:30:00Z',
        share: {
            visibility: 'public',
            link: 'https://sentinel.edu/exam/wd-midterm',
            embedCode: "<iframe src='...'></iframe>",
        },
        assignment: {
            studentIds: ['s1', 's2'],
            groupIds: ['g1'],
            dueDate: '2026-03-25',
            dueTime: '23:59',
            instructions: 'No external resources allowed.',
            notify: true,
        },
    },
    {
        id: 'exam-002',
        title: 'Database Systems Quiz 1',
        description: 'Focuses on SQL basics and normalization.',
        timeLimit: 30,
        passingScore: 80,
        status: 'draft',
        subject: 'Databases',
        duration: 30,
        studentsCount: 30,
        questionCount: 15,
        settings: {
            shuffleQuestions: false,
            showCorrectAnswers: true,
            allowReview: true,
            randomizeChoices: false,
        },
        questions: [],
        createdAt: '2026-03-10T09:00:00Z',
        updatedAt: '2026-03-10T09:00:00Z',
        share: {
            visibility: 'private',
            link: '',
            embedCode: '',
        },
        assignment: {
            studentIds: [],
            groupIds: [],
            dueDate: '',
            dueTime: '',
            instructions: '',
            notify: false,
        },
    },
    {
        id: 'exam-003',
        title: 'Legacy Intro to Java',
        description: 'Introduction to Java programming language concepts.',
        timeLimit: 120,
        passingScore: 70,
        status: 'archived',
        subject: 'Computer Science',
        duration: 120,
        studentsCount: 50,
        questionCount: 40,
        settings: {
            shuffleQuestions: true,
            showCorrectAnswers: true,
            allowReview: false,
            randomizeChoices: true,
        },
        questions: mockQuestions,
        createdAt: '2025-09-15T08:00:00Z',
        updatedAt: '2025-10-30T10:00:00Z',
        share: {
            visibility: 'private',
            link: '',
            embedCode: '',
        },
        assignment: {
            studentIds: [],
            groupIds: [],
            dueDate: '',
            dueTime: '',
            instructions: '',
            notify: false,
        },
    },
];
